Repository 1024pix/pix-api-data, pull requests merged in 2024-12, with the labels that each got.

#56 [FEATURE] mise à jour du csv d'exemple (pix-15295)
  docs/files/example-file-csv-query-insertion.csv
Labels: :rocket: Ready to Merge

#58 [DOC] Préciser la région dans les commandes du README
  README.md
Labels: :rocket: Ready to Merge

#63 [TECH] Proposition de modifications pour le setup de developement
  .gitignore
  .vscode/sample.launch.json
  README.md
  lib/application/authentication/index.ts
  lib/application/query/index.ts
  lib/common/db/seeds/seed.js
  lib/infrastructure/plugins/swagger.ts
  package.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team, team-certif

#59 [FEATURE] Ajout de la possibilité * comme paramètre (PIX-15594)
  lib/domain/models/QueryAccess.ts
  tests/acceptance/application/query_test.ts
  tests/integration/infrastructure/repositories/DatamartRepository_test.ts
  tests/unit/domain/models/QueryAccess_test.ts
Labels: :rocket: Ready to Merge, Tech Review OK
